apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-INST
spec:
  capacity:
    storage: SIZEGi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: "ext4"
    pdName: pd-ssd-disk-INST

